// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type CreateItemData = {
    /**
     * Payload containing name and age
     */
    body: {
        name: string;
        age: number;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/{id}';
};

export type CreateItemErrors = {
    /**
     * Bad Request
     */
    400: {
        message: string;
    };
};

export type CreateItemError = CreateItemErrors[keyof CreateItemErrors];

export type CreateItemResponses = {
    /**
     * Successful response
     */
    200: {
        message: string;
        name: string;
        age: number;
        id: number;
    };
};

export type CreateItemResponse = CreateItemResponses[keyof CreateItemResponses];
